# gdmflexiserver
# Autogenerated from man page /usr/share/man/man1/gdmflexiserver.1.gz
complete -c gdmflexiserver -s h -l help --description 'Show help options.'
complete -c gdmflexiserver -l help-all --description 'Show all help options.'
complete -c gdmflexiserver -l help-gtk --description 'Show \\s-1GTK+\\s0 Options . PP Application Options:.'
complete -c gdmflexiserver -s d -l debug --description 'Debugging output.'

