# needrestart
# Autogenerated from man page /usr/share/man/man1/needrestart.1.gz
complete -c needrestart -s v --description 'be more verbose.'
complete -c needrestart -s q --description 'be quiet.'
complete -c needrestart -s m --description 'set level of technical details.'
complete -c needrestart -s n --description 'set default answer to \'no\'.'
complete -c needrestart -s c --description 'config filename.'
complete -c needrestart -s r --description 'set restart mode.'
complete -c needrestart -s b --description 'enable batch mode.'
complete -c needrestart -s p --description 'nagios plugin mode: makes output and exit codes nagios compatible.'
complete -c needrestart -s f --description 'override debconf(7) frontend, sets the DEBIAN_FRONTEND environment variable t…'
complete -c needrestart -s u --description 'use preferred UI package (-u ? shows available packages).'
complete -c needrestart -s k --description 'check for obsolete kernel.'
complete -c needrestart -s l --description 'check for obsolete libraries ENVIRONMENT The following environment variables …'

