# scroll
# Autogenerated from man page /usr/local/man/man1/scroll.1
complete -c scroll -s h --description 'Shows usage of scroll.'
complete -c scroll -s M --description 'Set memory limit used for scrollbackbuffer to maximum.'
complete -c scroll -s m --description 'Set memory limit used for scrollbackbuffer to size.'

