# x-session-manager
# Autogenerated from man page /usr/share/man/man1/x-session-manager.1.gz
complete -c x-session-manager -l autostart --description 'The directory DIR to be searched for autostart . desktop files.'
complete -c x-session-manager -l session --description 'Use the applications defined in SESSION. session.  If not specified, gnome.'
complete -c x-session-manager -l builtin --description 'Use the legacy non-systemd method of managing the user session.'
complete -c x-session-manager -l systemd --description 'Use the systemd method of managing the user session.'
complete -c x-session-manager -l failsafe --description 'Run in fail-safe mode.  User-specified applications will not be started.'
complete -c x-session-manager -l debug --description 'Enable debugging code.'
complete -c x-session-manager -l whale --description 'Show the fail whale in a dialog for debugging it.'

